### ISSUE TITLE
paperclip in actix, doesn't work when we use actix macro #[post]

### ISSUE THREAD

**Issue by umaYnit** [wafflespeanut/paperclip#255]
Hi,I am use actix-web just now, and I have issue to integrate the library. My code is the following:
The following code doesn't work,it has compile error: **the trait \`Mountable\` is not implemented for \`echo_pet\`**

```rust
use actix_web::{App, HttpServer, post};
use paperclip::actix::{
    api_v2_operation, Apiv2Schema, OpenApiExt,
    web::{self, Json},
};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Apiv2Schema)]
struct Pet {
    name: String,
    id: Option<i64>,
}

#[api_v2_operation]
#[post("")]
async fn echo_pet(body: Json<Pet>) -> Result<Json<Pet>, ()> {
    Ok(body)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new()
        .wrap_api()
        .service(
            web::scope("/api").service(echo_pet)
        )
        .with_json_spec_at("/api/spec")
        .build()
    ).bind("127.0.0.1:8080")?
        .run().await
}
```

My Cargo.toml is like:

```toml
actix-web = "3.0"
paperclip = { git = "https://github.com/wafflespeanut/paperclip", features = ["actix-nightly"] }
serde = "1.0"
```

is this not supported now?
