### ISSUE TITLE
Actix: type alias makes Option<T> required

### ISSUE THREAD

**Issue by zd4y** [wafflespeanut/paperclip#257]
Having a schema like this:
```rust
type Email = Option<String>;

#[derive(Apiv2Schema, Serialize)]
struct User {
    id: i32,
    username: String,
    email: Email,
}
```

The `email` field is optional, but in the generated spec it is shown as required (`"required":["email","id","username"]`)

Full code:
```rust
use actix_web::{App, HttpServer};
use paperclip::actix::web::{self, Json};
use paperclip::actix::{api_v2_operation, Apiv2Schema, OpenApiExt};
use serde::Serialize;

type Email = Option<String>;

#[derive(Apiv2Schema, Serialize)]
struct User {
    id: i32,
    username: String,
    email: Email,
}

#[api_v2_operation]
async fn example() -> Json<User> {
    Json(User {
        id: 1,
        username: "john".into(),
        email: None,
    })
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .wrap_api()
            .route("/", web::get().to(example))
            .with_json_spec_at("/api/spec")
            .build()
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

Cargo.toml:
```toml
[dependencies]
actix-web = "3"
paperclip = { git = "https://github.com/wafflespeanut/paperclip", features = ["actix"] }
serde = { version = "1.0", features=["derive"] }
```

**Comment by omid** [comment]
AFAIK it's not easily possible, because paperclip will only see the struct definition which has one field with the type of `Email`, nothing else.

One simple way which may work for you is to put the Option inside the struct.

```
type Email = String;

#[derive(Apiv2Schema, Serialize)]
struct User {
    id: i32,
    username: String,
    email: Option<Email>,
}
```

Which makes more sense to me.
Because a new type is a new type! Which sometimes can be optional and sometimes cannot be.
I mean in your example, Email is an email, this new `type` is not an `optional email`, the optional meaning should appear in the context.

**Comment by wafflespeanut** [comment]
As @omid mentioned, it's not possible to do this in paperclip, because paperclip's proc macro can only see the parsed AST. One way to approach this (something I have in mind but need to work on implementation) is per-field override for OAPI spec schemas. It's possible to extend the macro to support serde-like syntax and have overrides.
```rust
struct MySchema {
    #[openapi(optional, format = "uuid", nullable)]
    field: String,
}
```
This will set UUID format, make the field optional and nullable in the schema.

**Comment by zd4y** [comment]
If this is desired behavior, it might be a good idea to document it. For example, structopt's docs:
> Pay attention that only literal occurrence of this types is special, for example `Option<T>` is special while `::std::option::Option<T>` is not.

Would you accept a PR of that?

If it's only a limitation of paperclip and want to fix it maybe you can check how the schemars crate does it. It supports the type alias

**Comment by omid** [comment]
I think your example won't work in schemars also.
Because you defined `type` here and you cannot `derive` types.

Do you have any working example of what you said, in `schemars`?

**Comment by zd4y** [comment]
@omid 
rocket_okapi uses schemars and this is from the generated spec:
```json
"required": [
          "id",
          "username"
        ],
```
If I remove the `Option` from the type alias `Email` then `"required"` will also contain `"email"`

Full code:
```rust
#![feature(decl_macro, proc_macro_hygiene)]

use rocket::get;
use rocket_contrib::json::Json;
use rocket_okapi::{openapi, routes_with_openapi, JsonSchema};
use serde::Serialize;

type Email = Option<String>;

#[derive(Serialize, JsonSchema)]
struct User {
    id: i32,
    username: String,
    email: Email,
}

#[openapi]
#[get("/users/<username>")]
fn get_user(username: String) -> Json<User> {
    Json(User {
        id: 1,
        username,
        email: None,
    })
}

fn main() {
    rocket::ignite()
        .mount("/", routes_with_openapi![get_user])
        .launch();
}
```
Cargo.toml:
```toml
[package]
name = "rocket-schemars-test"
version = "0.1.0"
authors = ["zd4y <ariasorozco03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rocket_contrib = "0.4.6"
rocket = "0.4.6"
rocket_okapi = "0.5"
schemars = "0.7"
okapi = { version = "0.4", features = ["derive_json_schema"] }
```
